[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc = "0.8.20"
optimizer = true
optimizer_runs = 1000
via_ir = true
gas_reports = ["*"]

# Configurar remappings para importaciones correctas
remappings = [
    'ds-test/=lib/forge-std/lib/ds-test/src/',
    'forge-std/=lib/forge-std/src/',
    'openzeppelin-contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/',
    'openzeppelin-contracts/=lib/openzeppelin-contracts/contracts/',
    'openzeppelin-erc20-basic/=lib/openzeppelin-contracts/contracts/token/ERC20/',
    'openzeppelin-erc20-extensions/=lib/openzeppelin-contracts-upgradeable/contracts/token/ERC20/extensions/',
    'openzeppelin-erc20/=lib/openzeppelin-contracts-upgradeable/contracts/token/ERC20/',
    'openzeppelin-math/=lib/openzeppelin-contracts/contracts/utils/math/',
    'openzeppelin-proxy/=lib/openzeppelin-contracts-upgradeable/contracts/proxy/utils/',
    'openzeppelin-utils/=lib/openzeppelin-contracts/contracts/utils/',
    '@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/',
    '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/',
    # Este es el remapping clave que falta
    'src/=src/',
]

# Asegurarse de que Foundry busque en las rutas correctas
fs_permissions = [{ access = "read-write", path = "./" }]

[rpc_endpoints]
ethereum = "${ETHEREUM_RPC_URL}"

[profile.etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }

[profile.fuzz]
runs = 1024
max_test_rejects = 65536
seed = '0x3e8'
dictionary_weight = 40
include_storage = true
include_push_bytes = true

[fuzz]
runs = 1024

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
